### ISSUE TITLE
¡SIMPLEZ!

### ISSUE THREAD

**Issue by CosasDePuma** [Obijuan/simplez-fpga#18]
¡Muy buenas!

Estoy realmente interesado en el funcionamiento del lenguaje ensamblador SIMPLEZ. Tengo un emulador mediante DOSBox para poder simular el comportamiento de los registros pero me falta documentación sobre cómo crear los programas.

La única que tengo hasta el momento es tu propia Wiki, por lo que me preguntaba si podrías decirme un par de sitios más donde haya ejemplos o docs

Muchisimas gracias por adelantado :)

**Comment by Obijuan** [comment]
Toda la documentación está en el libro:  "Curso de ordenadores : conceptos básicos de arquitectura y sistemas operativos". Ed. ETS Ingenieros Telecomunicaciones, UPM. 2005. Madrid. ISBN: 9788474023121
o cualquier otra versión posterior que hayan sacado
